Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 22, host: 2222, host_ip: "0.0.0.0", id: "ssh", auto_correct: true

  config.vm.synced_folder "../data", "/home/vagrant/vagrant_data"

  config.vm.provision "shell", path: "./../data/provision/common.sh"
  config.vm.provision "shell", path: "./../data/provision/upgrade.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "dev-with-docker"
    vb.cpus = 2
    vb.memory = "8192"
  end

end
