Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  config.vm.synced_folder "../data", "/home/vagrant/vagrant_data"

  config.vm.provision "shell", path: "./../data/provision/setup-dev.sh

  config.vm.provider "virtualbox" do |vb|
    vb.name = "dev"
    vb.cpus = 2
    vb.memory = "4096"
  end

end
